### ISSUE TITLE
'Quit' button on command 'Help' causes error

### ISSUE THREAD

**Issue by dragmine149** [dragmine149/DBJ7#1]
When using the Quit button on the help command, an error will appear in console. After looking at the files it seems to be that file [/src/util/paginator](https://github.com/dragmine149/DBJ7/blob/main/src/utils/paginator.py) on [line 343](https://github.com/dragmine149/DBJ7/blob/a1188cc30f9f7a4dd0dec51ffdaa1c1a79f1345e/src/utils/paginator.py#L343) causes this error.

Wanted to have this notted somewhere for later

**Comment by dragmine149** [comment]
![image](https://user-images.githubusercontent.com/69430730/193630443-27a1c0d7-2787-4e6a-a26f-c26ed47c4d26.png)

Console error logs, nothing in bot.log file

**Comment by timelessnesses** [comment]
done
