### ISSUE TITLE
Json data saved incorrectly causing it to break

### ISSUE THREAD

**Issue by dragmine149** [dragmine149/DBJ7#4]
idk how, but basically when doing CoinFlip game, `ll}` is added on to the end of the flip, breaking everything else.
(for that user) From looking at `src/utils/fileHandler` it seems to be that encoding it into whatever (on save) is causing this issue

**Comment by timelessnesses** [comment]
pause champ

**Comment by timelessnesses** [comment]
orjson and json both accepts json string as bytes now so this shouldn't be a problem now
