### ISSUE TITLE
Interactions don't have timeout error checking

### ISSUE THREAD

**Issue by dragmine149** [dragmine149/DBJ7#5]
If an interaction timesout, and the user tries to do something, the application will just fail.
This is fine if the bot has just been restarted, or very old interaction with elements that didn't get deleted / cleared (set view to none in `edit_original_message`) 
But if the user has just requested it, left for like a minute and came back then tries to interact with the bot. The bot will say interaction error without any reason.

This happens to pretty much everything single interaction.

**Comment by timelessnesses** [comment]
try `await discord.Interaction.response.defer()`

**Comment by timelessnesses** [comment]
timeout=0 or timeout=None should work :oyes:

**Comment by timelessnesses** [comment]
yea timeout=None works
